<script lang="ts">
	import { AppShell, AppBar } from '@skeletonlabs/skeleton-svelte';
</script>

<svelte:head>
	<title>{{projectName}}</title>
	<meta name="description" content="Generated by ai-agent-workflows" />
</svelte:head>

<AppShell>
	{#snippet appBar()}
		<AppBar>
			<svelte:fragment slot="lead">
				<a href="/" class="text-xl font-bold">{{projectName}}</a>
			</svelte:fragment>
		</AppBar>
	{/snippet}

	<div class="container mx-auto p-8">
		<div class="max-w-4xl mx-auto space-y-8">
			<div class="text-center space-y-4">
				<h1 class="h1">Welcome to {{projectName}}</h1>
				<p class="text-surface-600-300">
					A SvelteKit project scaffolded with ai-agent-workflows
				</p>
			</div>

			<nav class="card p-4 space-y-4">
				<a href="/reports" class="btn variant-ghost-surface w-full">
					<div class="text-left">
						<h2 class="h4">Reports →</h2>
						<p class="text-sm opacity-75">View and manage reports</p>
					</div>
				</a>
				<a href="/admin/feature-flags" class="btn variant-ghost-surface w-full">
					<div class="text-left">
						<h2 class="h4">Admin →</h2>
						<p class="text-sm opacity-75">Feature flags and audit logs</p>
					</div>
				</a>
			</nav>
		</div>
	</div>
</AppShell>
