/**
 * Materialization orchestrator - generates physical project files from resolved specs.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { resolveArchetype, type ResolvedContext } from './resolver.js';
import { generateFileTree, type FileTree } from './file-tree-generator.js';
import { buildTemplateVariables, renderTemplate, generatePackageJson, generateTsConfig, type TemplateVariables } from './template-renderer.js';
import { logger } from './logger.js';
import type { CreateContext } from '../create-project.js';

export interface MaterializationResult {
  projectPath: string;
  filesCreated: number;
  directoriesCreated: number;
}

/**
 * Orchestrates the materialization of a project from template specs.
 * 
 * Phases:
 * 1. Resolve - Get resolved context with template specs
 * 2. Plan - Generate file tree structure
 * 3. Prepare - Create all directories
 * 4. Materialize - Render and write all files
 * 5. Verify - Check all expected files exist
 */
export async function materializeProject(ctx: CreateContext): Promise<MaterializationResult> {
  logger.info('materialization_start', {
    projectName: ctx.projectName,
    outputPath: ctx.outputPath,
  });

  const resolved = resolveArchetype(ctx);

  validateOutputPath(ctx.outputPath);

  const fileTree = generateFileTree(resolved);

  await createDirectories(ctx.outputPath, fileTree);

  const variables = buildTemplateVariables(resolved);

  await materializeFiles(ctx.outputPath, fileTree, variables, resolved);

  await generateStandardsArtifacts(ctx.outputPath, variables, resolved);

  logger.info('materialization_complete', {
    projectPath: ctx.outputPath,
    directoriesCreated: fileTree.directories.length,
  });

  return {
    projectPath: ctx.outputPath,
    filesCreated: fileTree.files.length,
    directoriesCreated: fileTree.directories.length,
  };
}

function validateOutputPath(outputPath: string): void {
  if (fs.existsSync(outputPath)) {
    const files = fs.readdirSync(outputPath);
    if (files.length > 0) {
      throw new Error(`Output directory is not empty: ${outputPath}. Use --force to overwrite (not yet implemented).`);
    }
  }
}

async function createDirectories(outputPath: string, fileTree: FileTree): Promise<void> {
  logger.info('creating_directories', { count: fileTree.directories.length });

  for (const dir of fileTree.directories) {
    const fullPath = path.join(outputPath, dir);
    if (!fs.existsSync(fullPath)) {
      fs.mkdirSync(fullPath, { recursive: true });
      logger.debug('directory_created', { path: fullPath });
    }
  }
}

async function materializeFiles(
  outputPath: string,
  fileTree: FileTree,
  variables: TemplateVariables,
  resolved: ResolvedContext
): Promise<void> {
  logger.info('materializing_files', { count: fileTree.files.length });

  for (const fileNode of fileTree.files) {
    const targetPath = path.join(outputPath, fileNode.targetPath);

    if (fileNode.type === 'copy' && fileNode.sourcePath) {
      if (fs.existsSync(fileNode.sourcePath)) {
        const content = fs.readFileSync(fileNode.sourcePath, 'utf8');
        fs.writeFileSync(targetPath, content, 'utf8');
        logger.debug('file_copied', { source: fileNode.sourcePath, target: targetPath });
      } else {
        logger.warn('source_file_not_found', { path: fileNode.sourcePath });
      }
    } else if (fileNode.type === 'template' || fileNode.isTemplate) {
      if (fileNode.targetPath === 'package.json') {
        const content = generatePackageJson(variables);
        fs.writeFileSync(targetPath, content, 'utf8');
        logger.debug('file_generated', { target: targetPath, type: 'package.json' });
      } else if (fileNode.targetPath === 'tsconfig.json') {
        const content = generateTsConfig(variables);
        fs.writeFileSync(targetPath, content, 'utf8');
        logger.debug('file_generated', { target: targetPath, type: 'tsconfig.json' });
      }
    }
  }
}

async function generateStandardsArtifacts(
  outputPath: string,
  variables: TemplateVariables,
  resolved: ResolvedContext
): Promise<void> {
  logger.info('generating_standards_artifacts');

  await generateAgentsMd(outputPath, variables, resolved);
  await generateCursorRules(outputPath, variables, resolved);
  await generateConventionsMd(outputPath, variables, resolved);
}

async function generateAgentsMd(
  outputPath: string,
  variables: TemplateVariables,
  resolved: ResolvedContext
): Promise<void> {
  const content = `# Project Agents: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${variables.stackKey} v${variables.templateVersion}
Contracts: platform-contracts.yaml v${variables.contractsVersion}
Generated: ${variables.timestamp}

## Available Agents

### Orchestrator
- Role: Project coordination and task breakdown
- Trigger: Start of new feature or complex task
- Skills: requirements-clarification, architecture-planning
- Handoff: Delegates to implementers

### Stack Implementer (${variables.framework})
- Role: Implementation for ${variables.framework} stack
- Trigger: Handoff from orchestrator with implementation plan
- Skills: impl-${variables.stackKey}, test-${variables.stackKey}-unit
- Patterns:
  - State: ${variables.stateManagement ? `${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}` : 'N/A'}
  - Testing: ${variables.unitTestFramework || 'N/A'}

### Code Reviewer
- Role: Review implementations for quality and standards
- Trigger: Implementation complete, ready for review
- Skills: code-review, quality-assurance

### Tester
- Role: Write and run tests
- Trigger: Implementation complete or test failures
- Skills: test-backend-unit, test-frontend-unit
- Commands:
  - Unit: ${variables.unitTestCommand || 'N/A'}
  - E2E: ${variables.e2eTestCommand || 'N/A'}

## Stack Conventions

- Framework: ${variables.framework}
- Language: ${variables.language}
${variables.stateManagement ? `- State Management: ${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}` : ''}
- Testing: ${variables.unitTestFramework || 'N/A'}

## Required Capabilities

${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

## Workspace Skills

Skills can be installed at \`.github/skills/{family}/SKILL.md\`

Recommended families for this stack:
${variables.stackKey === 'nextjs' || variables.stackKey === 'sveltekit' || variables.stackKey === 'angular' ? '- impl-frontend\n- test-frontend-unit\n- test-e2e' : ''}
${variables.stackKey.startsWith('node_') || variables.stackKey === 'python' || variables.stackKey === 'go' ? '- impl-backend\n- test-backend-unit' : ''}
`;

  const agentsPath = path.join(outputPath, 'AGENTS.md');
  fs.writeFileSync(agentsPath, content, 'utf8');
  logger.info('generated_agents_md', { path: agentsPath });
}

async function generateCursorRules(
  outputPath: string,
  variables: TemplateVariables,
  resolved: ResolvedContext
): Promise<void> {
  const content = `# Cursor Rules: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${variables.stackKey} v${variables.templateVersion}
Contracts: platform-contracts.yaml v${variables.contractsVersion}

## Stack
- Framework: ${variables.framework} (${variables.stackKey})
- Language: ${variables.language}
- Template Version: ${variables.templateVersion}

${variables.stateManagement ? `## State Management (Frontend)
- Server State: ${variables.stateManagement.serverState}
  - Keep server state in query cache
  - Use ${variables.stateManagement.serverState} hooks for API data
- Client State: ${variables.stateManagement.clientState}
  - Keep UI state in feature-local stores
  - Avoid global state for feature-specific UI
- Form State: ${variables.stateManagement.formState}
  - Use ${variables.stateManagement.formState} for all forms
  - Use validation schemas
` : ''}
## Testing
- Unit Tests: \`${variables.unitTestCommand || 'npm test'}\` via ${variables.unitTestFramework || 'N/A'}
- E2E Tests: \`${variables.e2eTestCommand || 'npm run test:e2e'}\` via ${variables.e2eTestFramework || 'N/A'}
- Coverage: Target 80%+ for new code

## Required Capabilities
The following platform capabilities must remain implemented:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

Changes to these capabilities must maintain contract compatibility (see templates/shared/platform-contracts.yaml).

## Code Patterns
- Imports: Always at top of file, no inline imports
- Naming: Descriptive variable names, verb-first function names
- Error Handling: Use correlation IDs for all errors
- Observability: Emit telemetry for all key operations

## Platform Contracts
This project implements:
- Feature Flags API (CAP-FF-*)
- Reporting API (CAP-REP-*)
- Admin Dashboard (CAP-ADM-*)

Contract changes require template version bump.
`;

  const cursorDir = path.join(outputPath, '.cursor');
  if (!fs.existsSync(cursorDir)) {
    fs.mkdirSync(cursorDir, { recursive: true });
  }

  const rulesPath = path.join(cursorDir, 'rules');
  fs.writeFileSync(rulesPath, content, 'utf8');
  logger.info('generated_cursor_rules', { path: rulesPath });
}

async function generateConventionsMd(
  outputPath: string,
  variables: TemplateVariables,
  resolved: ResolvedContext
): Promise<void> {
  const content = `# Stack Conventions: ${variables.projectName}

## Overview
This document defines the engineering conventions for this ${variables.framework} project.
Generated: ${variables.timestamp}

## Technology Stack
- Framework: ${variables.framework}
- Language: ${variables.language}
${variables.stateManagement ? `- State Management: ${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}` : ''}
- Testing: ${variables.unitTestFramework || 'N/A'}

## Project Structure
\`\`\`
src/
  app/           # Routes and layouts
  features/      # Feature-based modules
  lib/           # Shared utilities
  components/    # Shared UI components
tests/
  unit/          # Unit tests
  e2e/           # End-to-end tests
\`\`\`

${variables.stateManagement ? `## State Management Patterns

### Server State
- Tool: ${variables.stateManagement.serverState}
- Location: Feature-level hooks (e.g., src/features/reports/use-reports.ts)
- Pattern: Query hooks for reads, mutation hooks for writes

### Client State
- Tool: ${variables.stateManagement.clientState}
- Location: Feature-level stores (e.g., src/features/reports/report-store.ts)
- Pattern: Slice-based stores, single responsibility
` : ''}
## Testing Conventions
- Unit: Test business logic and utilities
- Integration: Test feature modules with mocked dependencies
- E2E: Test critical user journeys

Commands:
- Unit: \`${variables.unitTestCommand || 'npm test'}\`
- E2E: \`${variables.e2eTestCommand || 'npm run test:e2e'}\`

## Required Capabilities
This project must maintain implementations for:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

See \`templates/shared/platform-contracts.yaml\` for API contracts.

## Code Style
- Naming: Use descriptive names (getUserById, not getData)
- Imports: Top of file, no inline imports
- Exports: Explicit exports, no export * unless necessary
- Comments: Explain why, not what
`;

  const docsDir = path.join(outputPath, 'docs');
  if (!fs.existsSync(docsDir)) {
    fs.mkdirSync(docsDir, { recursive: true });
  }

  const conventionsPath = path.join(docsDir, 'conventions.md');
  fs.writeFileSync(conventionsPath, content, 'utf8');
  logger.info('generated_conventions_md', { path: conventionsPath });
}
