/**
 * Templates for generated standards artifacts (AGENTS.md, .cursor/rules, conventions.md).
 * Extracted from materializer to keep orchestration logic clean.
 */
import type { TemplateVariables } from './template-renderer.js';

export function generateAgentsMdContent(variables: TemplateVariables): string {
  const stackKeyLabel = variables.stackKey || 'unknown';
  const frameworkLabel = variables.framework || 'Unknown Framework';
  const stateLabel = variables.stateManagement 
    ? `${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}`
    : 'N/A';
  
  const skillFamilies: string[] = [];
  if (variables.stackKey === 'nextjs' || variables.stackKey === 'sveltekit' || variables.stackKey === 'angular') {
    skillFamilies.push('- impl-frontend', '- test-frontend-unit', '- test-e2e');
  } else if (variables.stackKey === 'python' || variables.stackKey === 'go' || variables.stackKey === 'dotnet' || variables.stackKey === 'java' || variables.stackKey === 'rust' || variables.stackKey === 'node_nestjs') {
    skillFamilies.push('- impl-backend', '- test-backend-unit');
  }

  return `# Project Agents: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${stackKeyLabel} v${variables.templateVersion}
Contracts: platform-contracts.yaml v${variables.contractsVersion}
Generated: ${variables.timestamp}

## Available Agents

### Orchestrator
- Role: Project coordination and task breakdown
- Trigger: Start of new feature or complex task
- Skills: requirements-clarification, architecture-planning
- Handoff: Delegates to implementers

### Stack Implementer (${frameworkLabel})
- Role: Implementation for ${frameworkLabel} stack
- Trigger: Handoff from orchestrator with implementation plan
- Skills: impl-${stackKeyLabel}, test-${stackKeyLabel}-unit
- Patterns:
  - State: ${stateLabel}
  - Testing: ${variables.unitTestFramework || 'N/A'}

### Code Reviewer
- Role: Review implementations for quality and standards
- Trigger: Implementation complete, ready for review
- Skills: code-review, quality-assurance

### Tester
- Role: Write and run tests
- Trigger: Implementation complete or test failures
- Skills: test-backend-unit, test-frontend-unit
- Commands:
  - Unit: ${variables.unitTestCommand || 'N/A'}
  - E2E: ${variables.e2eTestCommand || 'N/A'}

## Stack Conventions

- Framework: ${frameworkLabel}
- Language: ${variables.language}
${variables.stateManagement ? `- State Management: ${stateLabel}` : ''}
- Testing: ${variables.unitTestFramework || 'N/A'}

## Required Capabilities

${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

## Workspace Skills

Skills can be installed at \`.github/skills/{family}/SKILL.md\`

Recommended families for this stack:
${skillFamilies.join('\n')}
`;
}

export function generateCursorRulesContent(variables: TemplateVariables): string {
  const stateManagementSection = variables.stateManagement ? `
## State Management (Frontend)
- Server State: ${variables.stateManagement.serverState}
  - Keep server state in query cache
  - Use ${variables.stateManagement.serverState} hooks for API data
- Client State: ${variables.stateManagement.clientState}
  - Keep UI state in feature-local stores
  - Avoid global state for feature-specific UI
- Form State: ${variables.stateManagement.formState}
  - Use ${variables.stateManagement.formState} for all forms
  - Use validation schemas
` : '';

  return `# Cursor Rules: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${variables.stackKey} v${variables.templateVersion}
Contracts: platform-contracts.yaml v${variables.contractsVersion}

## Stack
- Framework: ${variables.framework} (${variables.stackKey})
- Language: ${variables.language}
- Template Version: ${variables.templateVersion}
${stateManagementSection}
## Testing
- Unit Tests: \`${variables.unitTestCommand || 'npm test'}\` via ${variables.unitTestFramework || 'N/A'}
- E2E Tests: \`${variables.e2eTestCommand || 'npm run test:e2e'}\` via ${variables.e2eTestFramework || 'N/A'}
- Coverage: Target 80%+ for new code

## Required Capabilities
The following platform capabilities must remain implemented:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

Changes to these capabilities must maintain contract compatibility (see templates/shared/platform-contracts.yaml).

## Code Patterns
- Imports: Always at top of file, no inline imports
- Naming: Descriptive variable names, verb-first function names
- Error Handling: Use correlation IDs for all errors
- Observability: Emit telemetry for all key operations

## Platform Contracts
This project implements platform contracts for feature flags, reporting, and admin APIs.
Contract changes require template version bump.
`;
}

export function generateConventionsMdContent(variables: TemplateVariables): string {
  const stateManagementSection = variables.stateManagement ? `
## State Management Patterns

### Server State
- Tool: ${variables.stateManagement.serverState}
- Location: Feature-level hooks (e.g., src/features/reports/use-reports.ts)
- Pattern: Query hooks for reads, mutation hooks for writes

### Client State
- Tool: ${variables.stateManagement.clientState}
- Location: Feature-level stores (e.g., src/features/reports/report-store.ts)
- Pattern: Slice-based stores, single responsibility
` : '';

  return `# Stack Conventions: ${variables.projectName}

## Overview
This document defines the engineering conventions for this ${variables.framework} project.
Generated: ${variables.timestamp}

## Technology Stack
- Framework: ${variables.framework}
- Language: ${variables.language}
${variables.stateManagement ? `- State Management: ${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}` : ''}
- Testing: ${variables.unitTestFramework || 'N/A'}

## Project Structure
\`\`\`
src/
  app/           # Routes and layouts
  features/      # Feature-based modules
  lib/           # Shared utilities
  components/    # Shared UI components
tests/
  unit/          # Unit tests
  e2e/           # End-to-end tests
\`\`\`
${stateManagementSection}
## Testing Conventions
- Unit: Test business logic and utilities
- Integration: Test feature modules with mocked dependencies
- E2E: Test critical user journeys

Commands:
- Unit: \`${variables.unitTestCommand || 'npm test'}\`
- E2E: \`${variables.e2eTestCommand || 'npm run test:e2e'}\`

## Required Capabilities
This project must maintain implementations for:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

See \`templates/shared/platform-contracts.yaml\` for API contracts.

## Code Style
- Naming: Use descriptive names (getUserById, not getData)
- Imports: Top of file, no inline imports
- Exports: Explicit exports, no export * unless necessary
- Comments: Explain why, not what
`;
}
