/**
 * Templates for generated standards artifacts (AGENTS.md, .cursor/rules, conventions.md).
 * Extracted from materializer to keep orchestration logic clean.
 */
import type { TemplateVariables } from './template-renderer.js';

export function generateAgentsMdContent(variables: TemplateVariables): string {
  const stackKeyLabel = variables.stackKey || 'unknown';
  const frameworkLabel = variables.framework || 'Unknown Framework';
  
  let stateLabel: string;
  if (variables.preset) {
    const parts = [variables.preset.serverState, variables.preset.clientState].filter(Boolean);
    stateLabel = parts.join(' + ') || 'N/A';
  } else {
    stateLabel = variables.stateManagement 
      ? `${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}`
      : 'N/A';
  }
  
  // Skill families are now driven from template-spec
  const skillFamilies: string[] = variables.skillFamilies || [];

  const presetSection = variables.preset ? `Preset: ${variables.preset.name}
` : '';

  return `# Project Agents: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${stackKeyLabel} v${variables.templateVersion}
${presetSection}Contracts: platform-contracts.yaml v${variables.contractsVersion}
Generated: ${variables.timestamp}

## Available Agents

### Orchestrator
- Role: Project coordination and task breakdown
- Trigger: Start of new feature or complex task
- Skills: requirements-clarification, architecture-planning
- Handoff: Delegates to implementers

### Stack Implementer (${frameworkLabel})
- Role: Implementation for ${frameworkLabel} stack
- Trigger: Handoff from orchestrator with implementation plan
- Skills: impl-${stackKeyLabel}, test-${stackKeyLabel}-unit
- Patterns:
  - State: ${stateLabel}
  - Testing: ${variables.unitTestFramework || 'N/A'}

### Code Reviewer
- Role: Review implementations for quality and standards
- Trigger: Implementation complete, ready for review
- Skills: code-review, quality-assurance

### Tester
- Role: Write and run tests
- Trigger: Implementation complete or test failures
- Skills: test-backend-unit, test-frontend-unit
- Commands:
  - Unit: ${variables.unitTestCommand || 'N/A'}
  - E2E: ${variables.e2eTestCommand || 'N/A'}

## Stack Conventions

- Framework: ${frameworkLabel}
- Language: ${variables.language}
${variables.preset ? `- State Management: ${stateLabel} (${variables.preset.name})` : variables.stateManagement ? `- State Management: ${stateLabel}` : ''}
${variables.preset ? `- Styling: ${variables.preset.styling || 'N/A'}` : variables.styling ? `- Styling: ${variables.styling.framework}` : ''}
${variables.logging ? `- Logging: ${variables.logging.client || variables.logging.logger || 'N/A'}` : ''}
- Testing: ${variables.preset?.unitTesting || variables.unitTestFramework || 'N/A'}${variables.preset?.e2eTesting ? ` + ${variables.preset.e2eTesting}` : ''}

## Required Capabilities

${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

## Workspace Skills

Skills can be installed at \`.github/skills/{family}/SKILL.md\`

Recommended families for this stack:
${skillFamilies.map(family => `- ${family}`).join('\n')}
`;
}

export function generateCursorRulesContent(variables: TemplateVariables): string {
  const hasRequiredConventions = variables.requiredConventions && Object.keys(variables.requiredConventions).length > 0;

  let stateManagementSection = '';
  
  if (variables.preset) {
    stateManagementSection = `
## State Management (Frontend) — ${variables.preset.name}
${variables.preset.serverState ? `- Server State: ${variables.preset.serverState}
  - Keep server state in query cache
  - Use ${variables.preset.serverState} hooks for API data` : ''}
${variables.preset.clientState ? `- Client State: ${variables.preset.clientState}
  - Keep UI state in feature-local stores
  - Avoid global state for feature-specific UI` : ''}

## Styling — ${variables.preset.name}
${variables.preset.styling ? `- Framework: ${variables.preset.styling}
  - Use utility classes for styling
  - Organize shared styles in global CSS
  - Prefer composition over duplication` : ''}
`;
  } else if (variables.stateManagement) {
    stateManagementSection = `
## State Management${variables.requiredConventions?.state_management === 'required' ? ' (REQUIRED)' : ''}
- Server State: ${variables.stateManagement.serverState}
  - Keep server state in query cache
  - Use ${variables.stateManagement.serverState} hooks for API data
- Client State: ${variables.stateManagement.clientState}
  - Keep UI state in feature-local stores
  - Avoid global state for feature-specific UI
- Form State: ${variables.stateManagement.formState}
  - Use ${variables.stateManagement.formState} for all forms
  - Use validation schemas
`;
  }

  const presetSection = variables.preset ? `Preset: ${variables.preset.name}
` : '';

  // Only add styling section if not covered by preset
  const stylingSection = !variables.preset && variables.styling ? `
## Styling${variables.requiredConventions?.styling === 'required' ? ' (REQUIRED)' : ''}
- Framework: ${variables.styling.framework}
- Config: ${variables.styling.config}
${variables.styling.guidance ? variables.styling.guidance.map(g => `- ${g}`).join('\n') : ''}
` : '';

  const loggingSection = variables.logging ? `
## Logging${variables.requiredConventions?.logging === 'required' ? ' (REQUIRED)' : ''}
- ${variables.logging.client ? `Client: ${variables.logging.client}` : ''}${variables.logging.logger ? `Logger: ${variables.logging.logger}` : ''}
${variables.logging.guidance ? variables.logging.guidance.map(g => `- ${g}`).join('\n') : ''}
` : '';

  return `# Cursor Rules: ${variables.projectName}

Generated by ai-agent-workflows
Template: ${variables.stackKey} v${variables.templateVersion}
${presetSection}Contracts: platform-contracts.yaml v${variables.contractsVersion}

## Stack
- Framework: ${variables.framework} (${variables.stackKey})
- Language: ${variables.language}
- Template Version: ${variables.templateVersion}
${stateManagementSection}${stylingSection}${loggingSection}
## Testing${variables.preset ? ` — ${variables.preset.name}` : variables.requiredConventions?.testing === 'required' ? ' (REQUIRED)' : ''}
- Unit Tests: \`${variables.unitTestCommand || 'npm test'}\` via ${variables.unitTestFramework || 'N/A'}
- E2E Tests: \`${variables.e2eTestCommand || 'npm run test:e2e'}\` via ${variables.e2eTestFramework || 'N/A'}
- Coverage: Target 80%+ for new code

## Required Capabilities
The following platform capabilities must remain implemented:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

Changes to these capabilities must maintain contract compatibility (see templates/shared/platform-contracts.yaml).

${hasRequiredConventions ? `## Convention Requirements
This template enforces REQUIRED conventions for:
${Object.entries(variables.requiredConventions || {})
  .filter(([_, value]) => value === 'required')
  .map(([key]) => `- ${key.replace(/_/g, ' ')}`)
  .join('\n')}

Deviations from REQUIRED conventions must be documented and justified.

` : ''}## Code Patterns
- Imports: Always at top of file, no inline imports
- Naming: Descriptive variable names, verb-first function names
- Error Handling: Use correlation IDs for all errors
- Observability: Emit telemetry for all key operations

## Platform Contracts
This project implements platform contracts for feature flags, reporting, and admin APIs.
Contract changes require template version bump.
`;
}

export function generateConventionsMdContent(variables: TemplateVariables): string {
  let stateManagementSection = '';
  
  if (variables.preset) {
    stateManagementSection = `
## State Management Patterns — ${variables.preset.name}

${variables.preset.serverState ? `### Server State
- Tool: ${variables.preset.serverState}
- Location: Feature-level hooks (e.g., src/features/reports/use-reports.ts)
- Pattern: Query hooks for reads, mutation hooks for writes
` : ''}
${variables.preset.clientState ? `### Client State
- Tool: ${variables.preset.clientState}
- Location: Feature-level stores (e.g., src/features/reports/report-store.ts)
- Pattern: Slice-based stores, single responsibility
` : ''}
${variables.preset.styling ? `## Styling Patterns — ${variables.preset.name}

- Tool: ${variables.preset.styling}
- Location: Component-level utility classes, global styles in src/app/globals.css
- Pattern: Utility-first CSS, composition over duplication
` : ''}`;
  } else if (variables.stateManagement) {
    stateManagementSection = `
## State Management Patterns${variables.requiredConventions?.state_management === 'required' ? ' (REQUIRED)' : ''}

### Server State
- Tool: ${variables.stateManagement.serverState}
- Location: Feature-level hooks (e.g., src/features/reports/use-reports.ts)
- Pattern: Query hooks for reads, mutation hooks for writes

### Client State
- Tool: ${variables.stateManagement.clientState}
- Location: Feature-level stores (e.g., src/features/reports/report-store.ts)
- Pattern: Slice-based stores, single responsibility
`;
  }

  const presetSection = variables.preset ? `${variables.preset.name} preset applied.
` : '';

  // Only add styling section if not covered by preset
  const stylingSection = !variables.preset && variables.styling ? `
## Styling Conventions${variables.requiredConventions?.styling === 'required' ? ' (REQUIRED)' : ''}
- Framework: ${variables.styling.framework}
- Config: ${variables.styling.config}
${variables.styling.guidance ? variables.styling.guidance.map(g => `- ${g}`).join('\n') : ''}
` : '';

  const loggingSection = variables.logging ? `
## Logging Conventions${variables.requiredConventions?.logging === 'required' ? ' (REQUIRED)' : ''}
- ${variables.logging.client ? `Client: ${variables.logging.client}` : ''}${variables.logging.logger ? `Logger: ${variables.logging.logger}` : ''}
${variables.logging.guidance ? variables.logging.guidance.map(g => `- ${g}`).join('\n') : ''}
` : '';

  return `# Stack Conventions: ${variables.projectName}

## Overview
This document defines the engineering conventions for this ${variables.framework} project.
${presetSection}Generated: ${variables.timestamp}

> **Note**: Conventions marked as **(REQUIRED)** are enforced by the template and must not be changed without template version bump and team approval.

## Technology Stack
- Framework: ${variables.framework}
- Language: ${variables.language}
${variables.preset ? `- Preset: ${variables.preset.name}` : ''}
${variables.preset ? `- State Management: ${[variables.preset.serverState, variables.preset.clientState].filter(Boolean).join(' + ')}` : variables.stateManagement ? `- State Management: ${variables.stateManagement.serverState} + ${variables.stateManagement.clientState}` : ''}
${variables.preset?.styling ? `- Styling: ${variables.preset.styling}` : variables.styling ? `- Styling: ${variables.styling.framework}` : ''}
${variables.logging ? `- Logging: ${variables.logging.client || variables.logging.logger || 'N/A'}` : ''}
- Testing: ${variables.preset?.unitTesting || variables.unitTestFramework || 'N/A'}${variables.preset?.e2eTesting ? ` + ${variables.preset.e2eTesting}` : ''}

## Project Structure
\`\`\`
src/
  app/           # Routes and layouts
  features/      # Feature-based modules
  lib/           # Shared utilities
  components/    # Shared UI components
tests/
  unit/          # Unit tests
  e2e/           # End-to-end tests
\`\`\`
${stateManagementSection}${stylingSection}${loggingSection}
## Testing Conventions${variables.requiredConventions?.testing === 'required' ? ' (REQUIRED)' : ''}
- Unit: Test business logic and utilities
- Integration: Test feature modules with mocked dependencies
- E2E: Test critical user journeys

Commands:
- Unit: \`${variables.unitTestCommand || 'npm test'}\`
- E2E: \`${variables.e2eTestCommand || 'npm run test:e2e'}\`

## Required Capabilities
This project must maintain implementations for:
${variables.requiredCapabilities.map((cap) => `- ${cap}`).join('\n')}

See \`templates/shared/platform-contracts.yaml\` for API contracts.

## Code Style
- Naming: Use descriptive names (getUserById, not getData)
- Imports: Top of file, no inline imports
- Exports: Explicit exports, no export * unless necessary
- Comments: Explain why, not what
`;
}
